### PR TITLE
bugfix: S3UTILS-110 pass VersionId to PutMetadata route

### PR DESCRIPTION
**Pull request by jonathan-gramain**
Make sure the `PUT /_/backbeat/metadata` route gets the VersionId attribute, so that it is not confused in thinking we are attempting to update the master version.

Tested manually crrExistingObjects to check that there was no more removal of data on the source during replication.

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
ping

**Review by tmacro — APPROVED** [review]

**Review by watsaqat — APPROVED** [review]

**Comment by jonathan-gramain** [comment]
ping

**Comment by jonathan-gramain** [comment]
ping

**Pull request merged**
